FROM node:10.13-alpine

WORKDIR /usr/src/app

# RUN npm init

# RUN npm install --save-dev webpack webpack-cli webpack-dev-server \
#                 -g webpack webpack-cli \
#                 --save-dev @babel/core @babel/preset-env @babel/preset-react babel-loader \
#                 --save-dev react react-dom

# RUN npm create-react-app test_react_app

CMD ["sh"]
